Updating dependabot to support Javascript, Typescript and docker
bcgov/BC-Wallet-Demo pull request #237
Opened 2024-04-11 00:03 UTC by rajpalc7

2024-04-11 00:09 UTC, rajpalc7 commented
Hi @WadeBarnes , if this looks good , I can squash and merge.

2024-04-11 15:46 UTC, WadeBarnes requested changes
In addition to the items mentioned below, there is also a dockerfile in the root `/` directory.

2024-04-11 15:46 UTC, WadeBarnes commented on .github/dependabot.yml
> +        update-types: ["version-update:semver-major"]
I don't see any dependency manifests in the  `/cypress` folder.

2024-04-11 15:46 UTC, WadeBarnes commented on .github/dependabot.yml
> +        update-types: ["version-update:semver-major"]
I don't see any dependency manifests in the `/server/src` folder.

2024-04-11 21:20 UTC, rajpalc7 commented
Thanks @WadeBarnes I have made changes as per your suggestion.

2024-04-11 21:28 UTC, WadeBarnes requested changes
@rajpalc7, You were a little to aggressive with deleting the `npm` update sections in your last commit right before you rebased the commits.  You deleted one that was needed.

2024-04-11 22:15 UTC, rajpalc7 commented
Thanks @WadeBarnes , I have added the deleted one now.

2024-04-11 22:37 UTC, WadeBarnes approved these changes
Looks good to me.  I'll let @wadeking98 do a final review before merging.

2024-04-18 16:24 UTC, cvarjao requested changes

2024-04-18 16:24 UTC, cvarjao commented on .github/dependabot.yml
> +    directory: "/client"
`/client` is a submodule, and its lock file is managed top level. Please remove `/client` entry.

2024-04-18 16:24 UTC, cvarjao commented on .github/dependabot.yml
> +    directory: "/server"
`/server` is a submodule, and its lock file is managed top level. Please remove `/server` entry.

2024-04-18 16:34 UTC, rajpalc7 commented on .github/dependabot.yml
> +    directory: "/server"
Changes have been made

2024-04-18 16:34 UTC, rajpalc7 commented on .github/dependabot.yml
> +    directory: "/client"
Changes have been made

2024-04-18 17:11 UTC, cvarjao approved these changes

2024-04-18 18:08 UTC, merged