Feature law demo
bcgov/BC-Wallet-Demo pull request #31
Opened 2022-06-22 18:58 UTC by wadeking98

- added connectionless support to law proof request with BC Wallet
- added new character Joyce
- added accessibility to character selection screen
- added support to LSBC Proof requests from staging and mainNet

2022-06-22 19:26 UTC, amanji commented on client/src/pages/onboarding/OnboardingContainer.tsx
> +        Alice: {
Shouldn't this be configurable from the list of characters in the backend?

2022-06-22 20:51 UTC, wadeking98 commented on client/src/pages/onboarding/OnboardingContainer.tsx
> +        Alice: {
You're right, I moved it to the backend now

2022-06-23 18:54 UTC, amanji requested changes

2022-06-23 18:54 UTC, amanji commented on client/src/pages/onboarding/OnboardingContainer.tsx
> +    if (currentCharacter?.content[progress]) {
Would it be cleaner to do something like:

```js
  const charcterContent = currentCharacter?.content[progress]
  if (characterContent) {
    return characterContent)
  }
  return { ... }

2022-06-23 18:54 UTC, amanji commented on client/src/pages/onboarding/OnboardingContainer.tsx
> +          title={getCharacterContent(progress).title}
Could use a destructuring assignment like: `const {title, text} = getCharacterContent(progress)`

Then just pass `title` and `text` in the prop.

2022-06-23 18:54 UTC, amanji commented on client/src/pages/onboarding/steps/AcceptCredential.tsx
> +      <StepInformation title={title ? title : content.title} text={text ? text : content.text} />
Simpler to just say `title ?? content.title`

2022-06-23 23:27 UTC, wadeking98 commented on client/src/pages/onboarding/OnboardingContainer.tsx
> +    if (currentCharacter?.content[progress]) {
change completed

2022-06-23 23:28 UTC, wadeking98 commented on client/src/pages/onboarding/steps/AcceptCredential.tsx
> +      <StepInformation title={title ? title : content.title} text={text ? text : content.text} />
change completed

2022-06-23 23:33 UTC, amanji commented on server/src/content/businessWoman/useCases/Hotel.ts
Seems like this is identical to the student content

2022-06-23 23:33 UTC, amanji commented on client/src/pages/onboarding/steps/SetupConnection.tsx
> +      <StepInformation title={title ? title : content.title} text={text ? text : content.text} />
Could use nullish coalescing here too

2022-06-24 17:14 UTC, wadeking98 commented on client/src/pages/onboarding/steps/SetupConnection.tsx
> +      <StepInformation title={title ? title : content.title} text={text ? text : content.text} />
change completed

2022-06-24 19:21 UTC, amanji approved these changes

2022-06-24 19:28 UTC, merged